ports:
  - protocol: "HTTPS"
    targetProtocol: "HTTP"
    listeningPort: "443"
    targetPort: "32755"
    targetIP: "172.17.0.1"
    public: true
    path: "/"
    isAuth: false
  - protocol: "HTTPS"
    targetProtocol: "HTTP"
    listeningPort: "26934"
    targetPort: "40749"
    targetIP: "172.17.0.1"
    public: true
    path: "/"
    isAuth: true
    login: "root"
    password: "random_password"
    loginTitle: "phpMyAdmin"
environments:
  - key: "SOFTWARE_VERSION_TAG"
    value: "latest"
  - key: "NODE_ENV"
    value: "production"
  - key: "ADMIN_PASSWORD"
    value: "random_password"
  - key: "ADMIN_EMAIL"
    value: "[SERVICE_EMAIL]"
  - key: "SITES"
    value: "[SERVICE_DOMAIN]"
  - key: "APP_URL"
    value: "[SERVICE_DOMAIN]"
  - key: "ERP_HOST_NAME"
    value: "https://[SERVICE_DOMAIN]"
  - key: "SMTP_HOST"
    value: "172.17.0.1"
  - key: "SMTP_PORT"
    value: "25"
  - key: "SMTP_AUTH_STRATEGY"
    value: "NONE"
  - key: "SMTP_FROM_EMAIL"
    value: "[DOMAIN]@vm.elestio.app"

config:
  runTime: "dockerCompose"
  version: ""
  framework: ""
  buildCommand: "docker-compose build"
  buildDir: "/"
  runCommand: "docker-compose up -d"
  icon: ""
  screenshot: "ERPNext.png"
lifeCycleConfig:
  preInstallCommand: "./scripts/preInstall.sh"
  postInstallCommand: "./scripts/postInstall.sh"
  preBackupCommand: "./scripts/preBackup.sh"
  postBackupCommand: "./scripts/postBackup.sh"
  preRestoreCommand: "./scripts/preRestore.sh"
  postRestoreCommand: "./scripts/postRestore.sh"
  postDeployCommand: "./scripts/postDeploy.sh"
webUI:
  - url: "https://[SERVICE_DOMAIN]"
    label: "ERPNext Admin"
    login: "Administrator"
    password: "[ADMIN_PASSWORD]"
