version: "3"

services:
  traefik:
    image: traefik:v2.10 # Latest version of Traefik
    restart: always
    command:
      - "--providers.docker=true" # Enable Docker as a provider
      - "--entrypoints.web.address=:80" # Entry point for HTTP traffic
      - "--entrypoints.websecure.address=:443" # Entry point for HTTPS traffic (optional)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Enable TLS challenge (optional for HTTPS)
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com" # Email for SSL certs (optional)
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Path to store certs (optional)
    ports:
      - "80:80" # Traefik listening on port 80
      - "443:443" # Traefik listening on port 443 (for HTTPS)
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # To interact with Docker
      - "./letsencrypt:/letsencrypt" # For SSL certificate storage (optional)
    networks:
      - web

  backend:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs

  configurator:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "{}" > sites/common_site_config.json;
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host db;
        bench set-config -gp db_port 3306;
        bench set-config -g redis_cache "redis://redis-cache:6379";
        bench set-config -g redis_queue "redis://redis-queue:6379";
        bench set-config -g redis_socketio "redis://redis-socketio:6379";
        bench set-config -g host_name "${ERP_HOST_NAME}";
        bench set-config -gp socketio_port 9000;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
      ERP_HOST_NAME: ${ERP_HOST_NAME}
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    networks:
      - web

  create-site:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        wait-for-it -t 120 redis-socketio:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site frontend --no-mariadb-socket --admin-password=${ADMIN_PASSWORD} --db-root-password=${ADMIN_PASSWORD} --install-app erpnext --set-default;
        bench --site frontend install-app hrms;
    networks:
      - web

  db:
    image: elestio/mariadb:10.6
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost --password=${ADMIN_PASSWORD}
      interval: 1s
      retries: 15
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web

  frontend:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-ip.rule=Host(`34.45.42.215`)"
      - "traefik.http.routers.frontend-domain.rule=Host(`${APP_URL}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.frontend-ip.entrypoints=web"
      - "traefik.http.routers.frontend-domain.entrypoints=web"
    networks:
      - web

  queue-default:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - bench
      - worker
      - --queue
      - default
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    networks:
      - web

  queue-long:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - bench
      - worker
      - --queue
      - long
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    networks:
      - web

  queue-short:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - bench
      - worker
      - --queue
      - short
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs
    networks:
      - web

  redis-queue:
    image: elestio/redis:6.2
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: elestio/redis:6.2
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-socketio:
    image: elestio/redis:6.2
    restart: always
    volumes:
      - redis-socketio-data:/data

  scheduler:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - bench
      - schedule
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs

  websocket:
    image: elestio/erpnext:${SOFTWARE_VERSION_TAG}
    restart: always
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites
      - ./logs:/home/frappe/frappe-bench/logs

  pma:
    image: elestio/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "172.17.0.1:40749:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/db-data
      o: bind
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/redis-queue-data
      o: bind
  redis-cache-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/redis-cache-data
      o: bind
  redis-socketio-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/app/redis-socketio-data
      o: bind

networks:
  web:
    external: true
